[project]
name = "brownie"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dukpy>=0.5.0",
    "pyopengl>=3.1.10",
    "pysdl2>=0.9.17",
    "pysdl2-dll>=2.32.0",
    "skia-python>=138.0",
]
